/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace BinaryData
{

//================== drumkit.json ==================
static const unsigned char temp_binary_data_6[] =
"{\r\n"
"  \"backingTrack\": \"Musica_Jogo.wav\",\r\n"
"  \"pads\": [\r\n"
"    {\r\n"
"      \"note\": \"Pad_1\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_2\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_3\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_4\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_5\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_6\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_7\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_8\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_9\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_10\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_11\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_12\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_13\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_14\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_15\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_16\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_17\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_18\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_19\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_20\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_21\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_22\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_23\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_24\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_25\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_26\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_27\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_28\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_29\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_30\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_31\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_32\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_33\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_34\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_35\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_36\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_37\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_38\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_39\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_40\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_41\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_42\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_43\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_44\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_45\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_46\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_47\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_48\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_49\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_50\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_51\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_52\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_53\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_54\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_55\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_56\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_57\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_58\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_59\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_60\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_61\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_62\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_63\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_64\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    }\r\n"
"  ]\r\n"
"}";

const char* drumkit_json = (const char*) temp_binary_data_6;

//================== notes.json ==================
static const unsigned char temp_binary_data_7[] =
"{\r\n"
"  \"backingTrack\": \"Musica_Jogo.wav\",\r\n"
"  \"pads\": [\r\n"
"    {\r\n"
"      \"note\": \"Pad_1\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_2\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_3\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_4\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_5\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_6\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_7\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_8\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_9\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_10\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_11\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_12\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_13\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_14\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_15\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_16\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_17\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_18\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_19\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_20\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_21\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_22\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_23\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_24\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_25\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_26\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_27\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_28\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_29\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_30\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_31\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_32\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_33\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_34\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_35\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_36\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_37\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_38\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_39\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_40\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_41\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_42\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_43\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_44\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_45\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_46\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_47\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_48\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_49\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_50\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_51\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_52\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_53\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_54\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_55\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_56\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_57\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_58\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_59\",\r\n"
"      \"audioFile\": \"C.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_60\",\r\n"
"      \"audioFile\": \"D.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_61\",\r\n"
"      \"audioFile\": \"E.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_62\",\r\n"
"      \"audioFile\": \"F.mp3\",\r\n"
"      \"color\": \"ffffc107\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_63\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffd700\"\r\n"
"    },\r\n"
"    {\r\n"
"      \"note\": \"Pad_64\",\r\n"
"      \"audioFile\": \"G.mp3\",\r\n"
"      \"color\": \"ffffffff\"\r\n"
"    }\r\n"
"  ]\r\n"
"}";

const char* notes_json = (const char*) temp_binary_data_7;
}
